title: "Die Ewigen Chroniken"
description: "Entdecke die magische Welt von Elandor durch Märchen und Geschichten."
url: "https://ewigenchroniken.de"
baseurl: ""

collections:
  pages:
    output: true
  stories:
    output: true
    permalink: /stories/:title/
  books:
    output: true
    permalink: /books/:path/

defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: story

pagination:
  enabled: true
  per_page: 6
  permalink: '/stories/page:num/'
  collection: 'stories'

permalink: none



plugins:
  - jekyll-paginate-v2
