title: "Die Ewigen Chroniken"
description: "Entdecke die magische Welt von Elandor durch Märchen und Geschichten."
url: "https://ewigenchroniken.de/"
baseurl: "" # Verwende "/" wenn die Website in einem Unterverzeichnis liegt
