title: "Die Ewigen Chroniken"
description: "Entdecke die magische Welt von Elandor durch Märchen und Geschichten."
url: "https://ewigenchroniken.de"
baseurl: "" # Setze hier "/unterverzeichnis", falls die Seite in einem Unterverzeichnis läuft

collections:
  pages:
    output: true
  stories:
    output: true
permalink: pretty
