title: "Die Ewigen Chroniken"
description: "Entdecke die magische Welt von Elandor durch Märchen und Geschichten."
url: "https://ewigenchroniken.de"
baseurl: "" # Falls die Seite in einem Unterverzeichnis liegt, ändere dies entsprechend

collections:
  pages:
    output: true
  stories:
    output: true
    permalink: /_stories/:title/
  books:
    output: true
    permalink: /books/:path/
defaults:
  - scope:
      path: ""
      type: "_stories"
    values:
      layout: story

permalink: pretty


